# Generated by Django 6.0.3 on 2026-03-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('size', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('shelf_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.material')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShelfSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.CharField(max_length=20)),
                ('slot_index', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='dashboard.delivery')),
            ],
            options={
                'ordering': ['shelf_id', 'slot_index'],
                'unique_together': {('shelf_id', 'slot_index')},
            },
        ),
    ]
