# Generated by Django 6.0.3 on 2026-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfslot',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
