# Generated by Django 6.0.3 on 2026-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_shelfslot_stored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
