# Generated by Django 6.0.3 on 2026-03-28 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delivery_delete_reason_alter_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('product', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=200)),
                ('delivery_batch', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('defected', 'Defected')], max_length=20)),
                ('processing_time', models.FloatField(default=0)),
                ('total_energy', models.FloatField(default=0)),
                ('total_scrap', models.FloatField(default=0)),
                ('quality', models.CharField(default='PASS', max_length=10)),
                ('defect_machine', models.CharField(blank=True, max_length=200)),
                ('defect_machine_id', models.CharField(blank=True, max_length=20)),
                ('defect_type', models.CharField(blank=True, max_length=200)),
                ('defect_cause', models.CharField(blank=True, max_length=300)),
                ('stages_completed', models.IntegerField(default=5)),
                ('stage_data', models.JSONField(blank=True, default=list)),
                ('stage_timestamps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
