# Generated by Django 6.0.3 on 2026-03-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_manufacturingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20, unique=True)),
                ('machine_name', models.CharField(max_length=200)),
                ('usage_count', models.IntegerField(default=0)),
                ('failure_threshold', models.IntegerField(default=500)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to='dashboard.delivery'),
        ),
        migrations.CreateModel(
            name='ScrapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=200)),
                ('machine_id', models.CharField(max_length=20)),
                ('machine_index', models.IntegerField()),
                ('scrap_type', models.CharField(max_length=100)),
                ('scrap_rate', models.FloatField()),
                ('material_name', models.CharField(blank=True, max_length=200)),
                ('delivery_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_events', to='dashboard.manufacturingorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
