# Generated by Django 6.0.3 on 2026-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinehealth',
            name='detail_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
