# Generated by Django 6.0.3 on 2026-03-28 08:28

from django.db import migrations, models


def assign_positions(apps, schema_editor):
    MachineHealth = apps.get_model('dashboard', 'MachineHealth')
    for i, m in enumerate(MachineHealth.objects.order_by('machine_id')):
        m.position = i
        m.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_machinehealth_detail_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinehealth',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='machinehealth',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(assign_positions, migrations.RunPython.noop),
    ]
