# Generated by Django 6.0.3 on 2026-03-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_machinehealth_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('delivery', 'Delivery'), ('manufacturing', 'Manufacturing'), ('scrap', 'Scrap'), ('machine', 'Machine'), ('material', 'Material'), ('warehouse', 'Warehouse'), ('shipment', 'Shipment'), ('threshold', 'Threshold')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.delivery')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.machinehealth')),
                ('manufacturing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.manufacturingorder')),
                ('scrap_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='dashboard.scrapevent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='dashboard_g_timesta_a0014b_idx'), models.Index(fields=['-timestamp', 'severity'], name='dashboard_g_timesta_4237d9_idx')],
            },
        ),
    ]
