# Generated by Django 6.0.3 on 2026-03-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='grid_cols',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='grid_rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='height_m',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='layout_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='length_m',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('custom', 'Custom')], default='rectangle', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelves_per_unit',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='slots_per_shelf',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='width_m',
            field=models.FloatField(default=50.0),
        ),
        migrations.CreateModel(
            name='WarehouseCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('cell_type', models.CharField(choices=[('storage', 'Storage Unit'), ('wall', 'Wall'), ('walkway', 'Walkway'), ('dock', 'Loading Dock'), ('empty', 'Empty Space')], default='empty', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=5)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='dashboard.warehouse')),
            ],
            options={
                'ordering': ['row', 'col'],
                'unique_together': {('warehouse', 'row', 'col')},
            },
        ),
    ]
