# Generated by Django 6.0.3 on 2026-03-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_warehouse_grid_cols_warehouse_grid_rows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection')], max_length=20)),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True, default='')),
                ('technician_notes', models.TextField(blank=True, default='')),
                ('next_scheduled', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entries', to='dashboard.machinehealth')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
