# Generated by Django 6.0.3 on 2026-03-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_maintenanceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfslot',
            name='manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_slots', to='dashboard.manufacturingorder'),
        ),
    ]
