from django.urls import path
from . import views, ai_views

app_name = 'dashboard'

urlpatterns = [
    path('', views.profile_select, name='profile_select'),
    path('set-profile/', views.set_profile, name='set_profile'),
    path('clear-profile/', views.clear_profile, name='clear_profile'),
    path('operator/', views.operator_home, name='operator_home'),
    path('operator/dashboard/', views.operator_dashboard, name='operator_dashboard'),
    path('operator/delivery/', views.operator_delivery, name='operator_delivery'),
    path('operator/materials/', views.operator_materials, name='operator_materials'),
    path('operator/warehouse/', views.operator_warehouse, name='operator_warehouse'),
    path('operator/warehouse/<int:warehouse_id>/', views.operator_warehouse_view, name='operator_warehouse_view'),
    path('operator/finished-goods/', views.operator_finished_goods, name='operator_finished_goods'),
    path('legacy/', views.index, name='index'),
    path('delivery/', views.delivery, name='delivery'),
    path('manufacturing/', views.manufacturing, name='manufacturing'),
    path('materials/', views.materials, name='materials'),
    path('api/shelf-info/', views.shelf_info, name='shelf_info'),
    path('api/mark-stored/', views.mark_stored, name='mark_stored'),
    path('api/generate-delivery/', views.generate_delivery, name='generate_delivery'),
    path('api/add-delivery/', views.add_delivery, name='add_delivery'),
    path('api/warehouse-map/', views.warehouse_map, name='warehouse_map'),
    path('api/warehouse-stats/', views.warehouse_stats, name='warehouse_stats'),
    path('api/delivery-statuses/', views.delivery_statuses, name='delivery_statuses'),
    path('api/delete-delivery/', views.delete_delivery, name='delete_delivery'),
    path('api/deleted-deliveries/', views.deleted_deliveries, name='deleted_deliveries'),
    path('api/save-manufacturing-order/', views.save_manufacturing_order, name='save_manufacturing_order'),
    path('api/consume-pallet/', views.consume_pallet, name='consume_pallet'),
    path('api/store-finished-order/', views.store_finished_order, name='store_finished_order'),
    # Logs
    path('logs/', views.logs, name='logs'),
    # Machine Health
    path('health/', views.health, name='health'),
    path('api/machine-health-data/', views.machine_health_data, name='machine_health_data'),
    path('api/update-failure-threshold/', views.update_failure_threshold, name='update_failure_threshold'),
    path('api/reset-machine/', views.reset_machine, name='reset_machine'),
    path('api/increment-machine-usage/', views.increment_machine_usage, name='increment_machine_usage'),
    path('api/update-machine-detail/', views.update_machine_detail, name='update_machine_detail'),
    path('api/add-machine/', views.add_machine, name='add_machine'),
    path('api/delete-machine/', views.delete_machine, name='delete_machine'),
    path('api/reorder-machines/', views.reorder_machines, name='reorder_machines'),
    # Warehouse selection
    path('api/warehouses/', views.warehouse_list, name='warehouse_list'),
    path('api/set-warehouse/', views.set_warehouse, name='set_warehouse'),
    # Warehouse layout
    path('warehouse/<int:warehouse_id>/setup/', views.warehouse_setup, name='warehouse_setup'),
    path('api/warehouse-layout/<int:warehouse_id>/', views.warehouse_layout, name='warehouse_layout'),
    path('api/warehouse-layout/<int:warehouse_id>/save/', views.warehouse_layout_save, name='warehouse_layout_save'),
    path('api/warehouse-layout/<int:warehouse_id>/apply-shape/', views.warehouse_apply_shape, name='warehouse_apply_shape'),
    path('api/warehouse-layout/<int:warehouse_id>/toggle-cell/', views.warehouse_toggle_cell, name='warehouse_toggle_cell'),
    path('api/warehouse-layout/<int:warehouse_id>/auto-assign/', views.warehouse_auto_assign, name='warehouse_auto_assign'),
    # Settings
    path('settings/', views.settings_page, name='settings'),
    path('api/save-ai-settings/', views.save_ai_settings, name='save_ai_settings'),
    # Maintenance Technician
    path('maintenance/', views.maintenance_home, name='maintenance_home'),
    path('maintenance/dashboard/', views.maintenance_dashboard, name='maintenance_dashboard'),
    path('maintenance/machines/', views.maintenance_machines, name='maintenance_machines'),
    path('maintenance/log/', views.maintenance_log_page, name='maintenance_log'),
    path('maintenance/logs/', views.maintenance_logs, name='maintenance_logs'),
    path('api/maintenance-entry/', views.api_create_maintenance_entry, name='api_create_maintenance_entry'),
    # Production Supervisor
    path('production/', views.production_home, name='production_home'),
    path('production/dashboard/', views.production_dashboard, name='production_dashboard'),
    path('production/orders/', views.production_orders, name='production_orders'),
    path('production/machines/', views.production_machines, name='production_machines'),
    path('production/warehouses/', views.production_warehouses, name='production_warehouses'),
    path('production/logs/', views.production_logs, name='production_logs'),
    path('production/ready-delivery/', views.production_ready_delivery, name='production_ready_delivery'),
    path('production/warehouses/<int:warehouse_id>/editor/', views.production_warehouse_editor, name='production_warehouse_editor'),
    path('production/pipeline/', views.production_pipeline, name='production_pipeline'),
    # AI Chat
    path('api/ai/chat/', ai_views.chat_stream, name='ai_chat'),
    path('api/ai/chat/history/', ai_views.chat_history, name='ai_chat_history'),
    path('api/ai/chat/clear/', ai_views.chat_clear, name='ai_chat_clear'),
]
